networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
  rede-compartilhada:
      external: true
services:
  db:
    image: postgres:16-alpine
    container_name: nanommo-postgres
    environment:
      POSTGRES_USER: nanommo
      POSTGRES_PASSWORD: nanommo_dev_password
      POSTGRES_DB: nanommo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nanommo"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rede-compartilhada

  redis:
    image: redis:7-alpine
    container_name: nanommo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rede-compartilhada

  backend:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: nanommo-backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "nanommo"
      DB_PASSWORD: "nanommo_dev_password"
      DB_NAME: "nanommo"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      JWT_SECRET: "dev_secret_key_change_in_production"
      COOKIE_SECRET: "dev_cookie_secret_change_in_production"
    ports:
      - "3000:3000"
    # volumes:
    #   - ./apps/api/src:/app/apps/api/src
    networks:
      - rede-compartilhada

volumes:
  postgres_data:
  redis_data:
